import type { Metadata } from 'next';
import './globals.css';
import SmoothScroll from '@/components/General/SmoothScroll';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <meta name='viewport' content='user-scalable=no, width=device-width, initial-scale=1.0' />
      <body>
        <SmoothScroll>
          <main className='flex flex-col items-center'>{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
