import type { Metadata } from 'next';
import './globals.css';
import SmoothScroll from '@/context/SmoothScroll';
import { Toaster } from 'sonner';
import { Navbar } from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import { NextUIProvider } from '@nextui-org/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <meta
        name='viewport'
        content='user-scalable=no, width=device-width, initial-scale=1.0'
      />
      <body>
        <SmoothScroll>
          <NextUIProvider>
            <Navbar />
            <main className='flex flex-col items-center'>{children}</main>
            <Footer />
            <Toaster richColors duration={2000} />
          </NextUIProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
